---
name: Release
'on':
  push:
    tags:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [3.16, 3.17]
        version_minor_release: [0]
        include:
          - version_branch: 3.16
            version_minor_release: 1
          - version_branch: 3.16
            version_minor_release: 2
          - version_branch: 3.16
            version_minor_release: 3
          - version_branch: 3.16
            version_minor_release: 4

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Test building image
        run: docker build -t docker-alpine-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }} ./alpine${{ matrix.version_branch }}/. --build-arg ALPINE_VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
      
      - name: Run the built image
        run: docker run --name test-container --detach --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro docker-alpine-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

      - name: Verify Ansible is accessible in the built image
        run: docker exec --tty test-container env TERM=xterm ansible --version

  tag-release:
    name: Release for tags
    runs-on: ubuntu-latest
    needs: test

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [3.16, 3.17]
        version_minor_release: [0]
        include:
          - version_branch: 3.16
            version_minor_release: 1
          - version_branch: 3.16
            version_minor_release: 2
          - version_branch: 3.16
            version_minor_release: 3
          - version_branch: 3.16
            version_minor_release: 4

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v2

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          build-args: ALPINE_VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./
          file: ./alpine${{ matrix.version_branch }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: kirillzak/docker-alpine-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

  latest-release:
    name: Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v2

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          build-args: ALPINE_VERSION=3.17.0
          context: ./
          file: ./alpine3.17/Dockerfile
          platforms: linux/amd64
          push: true
          tags: kirillzak/docker-alpine-ansible:latest