---
name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    strategy: 
      fail-fast: false

      matrix:
        version_branch: [3.16, 3.17, 3.18, 3.19]
        version_minor_release: [0, 1, 2, 3, 4, 5, 6, 7]
        exclude:
          - version_branch: 3.17
            version_minor_release: 6
          - version_branch: 3.17
            version_minor_release: 7
          - version_branch: 3.18
            version_minor_release: 1
          - version_branch: 3.18
            version_minor_release: 5
          - version_branch: 3.18
            version_minor_release: 6
          - version_branch: 3.18
            version_minor_release: 7
          - version_branch: 3.19
            version_minor_release: 1
          - version_branch: 3.19
            version_minor_release: 2
          - version_branch: 3.19
            version_minor_release: 3
          - version_branch: 3.19
            version_minor_release: 4
          - version_branch: 3.19
            version_minor_release: 5
          - version_branch: 3.19
            version_minor_release: 6
          - version_branch: 3.19
            version_minor_release: 7

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Test building image
        run: docker build -t docker-alpine-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }} ./alpine${{ matrix.version_branch }}/. --build-arg ALPINE_VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
      
      - name: Run the built image
        run: docker run --name test-container --detach --privileged --volume /sys/fs/cgroup:/sys/fs/cgroup:ro docker-alpine-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

      - name: Verify Ansible is accessible in the built image
        run: docker exec --tty test-container env TERM=xterm ansible --version

  tag-release:
    name: Release tags
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      packages: write

    strategy: 
      fail-fast: false

      matrix:
        platform:
          - linux/386
          - linux/amd64
        version_branch: [3.16, 3.17, 3.18, 3.19]
        version_minor_release: [0, 1, 2, 3, 4, 5, 6, 7]
        exclude:
          - version_branch: 3.17
            version_minor_release: 6
          - version_branch: 3.17
            version_minor_release: 7
          - version_branch: 3.18
            version_minor_release: 1
          - version_branch: 3.18
            version_minor_release: 5
          - version_branch: 3.18
            version_minor_release: 6
          - version_branch: 3.18
            version_minor_release: 7
          - version_branch: 3.19
            version_minor_release: 1
          - version_branch: 3.19
            version_minor_release: 2
          - version_branch: 3.19
            version_minor_release: 3
          - version_branch: 3.19
            version_minor_release: 4
          - version_branch: 3.19
            version_minor_release: 5
          - version_branch: 3.19
            version_minor_release: 6
          - version_branch: 3.19
            version_minor_release: 7

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v2

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          build-args: ALPINE_VERSION=${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
          context: ./
          file: ./alpine${{ matrix.version_branch }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            kirillzak/docker-alpine-ansible:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}
            ghcr.io/${{ github.repository }}:${{ matrix.version_branch }}.${{ matrix.version_minor_release }}

  latest-release:
    name: Latest release
    runs-on: ubuntu-latest
    needs: test

    strategy: 
      fail-fast: false

      matrix:
        platform:
          - linux/386
          - linux/amd64

    steps:
      - name: Checkout out the codebase
        uses: actions/checkout@v3

      - name: Add Qemu
        uses: docker/setup-qemu-action@v2

      - name: Add Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          build-args: ALPINE_VERSION=3.19.0
          context: ./
          file: ./alpine3.19/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            kirillzak/docker-alpine-ansible:latest
            ghcr.io/${{ github.repository }}:latest
